export const externalCategory = [
  {
    Mobiles: {
      title: ["Tablets", "Accessories", "Smart Watches", "Mobile Phones"],
      options: {
        Accessories: [
          "Charging Cables",
          "Converters",
          "Chargers",
          "Screens",
          "Screen Protectors",
          "Mobile Stands",
          "Ring Lights",
          "Selfie Sticks",
          "Power Banks",
          "Headphones",
          "Earphones",
          "Covers & Cases",
          "External Memory",
          "Other Accessories",
        ],
      },
    },
    Vehicles: {
      title: [
        "Cars",
        "Cars on Installments",
        "Cars Accessories",
        "Spare Parts",
        "Buses, Vans & Trucks",
        "Rickshaw & Chingchi",
        "Other Vehicles",
        "Boats",
        "Tractors & Trailers",
      ],
    },
    "Property for Sales": {
      title: [
        "Land & Plots",
        "Houses",
        "Apartments & Flats",
        "Shops - Offices - Commercial Space",
        "Portions & Floors",
      ],
    },
    "Property for Rent": {
      title: [
        "Houses",
        "Apartments & Flats",
        "Portions & Floors",
        "Shops - Offices - Commercial Space",
        "Rooms",
        "Roommates & Paying Guests",
        "Vacation Rentals - Guest Houses",
        "Land & Plots",
      ],
    },
    "Electronics and Home Appliances": {
      title: [
        "Computers & Accessories",
        "Games & Entertainment",
        "Cameras & Accessories",
        "Televisions & Accessories",
        "Audio & Video",
        "AC & Coolers",
        "Fans",
        "Heaters & Geysers",
        "Air Purifiers & Humidifiers",
        "Washing Machines & Dryers",
        "Irons & Steamers",
        "Sewing Machines",
        "Generators, UPS & Power Solutions",
        "Other Home Appliances",
        "Refrigerators & Freezers",
        "Water Dispensers",
        "Microwaves & Ovens",
        "Kitchen Appliances",
      ],
      options: {
        "Computers & Accessories": [
          "Desktops",
          "Workstations",
          "Gaming PCs",
          "Laptops",
          "Computer & Laptop Accessories",
          "Computer Components",
          "Servers",
          "Softwares",
          "Networking",
          "Printers & Photocopiers",
          "Inks & Toners",
        ],
      },
    },
    Bikes: {
      title: [
        "Motorcycles",
        "Spare Parts",
        "Bikes Accessories",
        "Bicycles",
        "ATV & Quads",
        "Scooters",
      ],
      options: {
        Motorcycles: [
          "Standard",
          "Electric Bikes",
          "Sports & Heavy Bikes",
          "Cafe Racers",
          "Cruisers",
          "Trail",
          "Others",
        ],
        "Spare Parts": [
          "Air Filters",
          "Carburetors",
          "Bearings",
          "Side Mirrors",
          "Motorcycle Batteries",
          "Switches",
          "Lighting",
          "Cylinders",
          "Clutches",
          "Pistons",
          "Chain, Covers & Sprockets",
          "Brakes",
          "Handle Bars & Grips",
          "Levers",
          "Seats",
          "Exhausts",
          "Fuel Tanks",
          "Horns",
          "Speedometers",
          "Plugs",
          "Stands",
          "Tyres & Tubes",
          "Other Spare Parts",
        ],
        "Bikes Accessories": [
          "Bicycle Air Pumps",
          "Oils / Lubricants",
          "Bike Covers",
          "Bike Gloves",
          "Helmets",
          "Tail Boxes",
          "Bike Jackets",
          "Bike Locks",
          "Safe Guards",
          "Other Bike Accessories",
        ],
        Bicycles: [
          "Road Bikes",
          "Mountain Bikes",
          "Hybrid Bikes",
          "BMX Bikes",
          "Electric Bicycles",
          "Folding Bikes",
          "Other Bicycles",
        ],
      },
    },
    "Business, Industrial & Agriculture": {
      title: [
        "Food & Restaurants",
        "Medical & Pharma",
        "Other Business & Industry",
        "Construction & Heavy Machinery",
        "Trade & Industrial Machinery",
        "Agriculture",
      ],
      options: {
        "Business for Sales": [
          "Mobile Shops",
          "Water Plants",
          "Beauty Salons",
          "Grocery Stores",
          "Hotels & Restaurants",
          "Pharmacies",
          "Snooker Clubs",
          "Cosmetic & Jewellery Shops",
          "Gyms",
          "Clinics",
          "Franchises",
          "Gift & Toy Shops",
          "Petrol Pumps",
          "Auto Part Shops",
          "Other Businesses",
        ],
        "Foods and Resturents": [
          "Baking Equipments",
          "Food Display Counters",
          "Ovens & Tandoor",
          "Fryers",
          "Tables & Platforms",
          "Fruit & Vegetable Machines",
          "Chillers",
          "Food Stalls",
          "Delivery Bags",
          "Crockery & Cutlery",
          "Ice cream Machines",
          "Other Restaurant Equipments",
        ],
        "Construction & Heavy Machinery": [
          "Construction Material",
          "Concrete Grinders",
          "Drill Machines",
          "Loaders",
          "Concrete Mixers",
          "Road Roller",
          "Cranes",
          "Construction Lifters",
          "Pavers",
          "Excavators",
          "Concrete Cutters",
          "Compactors",
          "Water Pumps",
          "Bulldozers",
          "Air Compressors",
          "Dump Truck",
          "Motor Graders",
          "Other Heavy Equipments",
        ],
        Agriculture: [
          "Farm, Machinery and Equipments",
          "Seeds",
          "Crops",
          "Pesticides & Fertilizers",
          "Plants & Trees",
          "Other Agriculture",
          "Silage",
        ],
        "Medical & Pharma": [
          "Ultrasound Machines",
          "Surgical Masks",
          "Patient Beds",
          "Wheelchairs",
          "Oxygen Concentrators",
          "Oxygen Cylinders",
          "Pulse Oximeters",
          "Hearing Aids",
          "Blood Pressure Monitors",
          "Thermometers",
          "Walkers",
          "Nebulizers",
          "Sanitizers",
          "Surgical Gloves",
          "X-ray Machines",
          "Lighting - Medical",
          "Medicines",
          "Glucometers",
          "Breast Pumps",
          "Commode Chairs",
          "Surgical Instruments",
          "Medical Scrubs",
          "Microscopes",
          "Other Medical Supplies",
        ],
        "Trade & Industrial Machinery": [
          "Woodworking Machines",
          "Currency Counting Machines",
          "Plastic & Rubber Processing Machines",
          "Industry Laser Machines",
          "Molding Machines",
          "Packaging Machines",
          "Welding Equipments",
          "Paper Machines",
          "Air Compressors",
          "Sealing Machines",
          "Lathe Machines",
          "Liquid Filling Machines",
          "Marking Machines",
          "Textile Machinery",
          "Sewing Machines",
          "Knitting Machines",
          "Embroidery Machines",
          "Printing Machines",
          "Other Business & Industrial Machines",
        ],
      },
    },
    Services: {
      title: [
        "Architecture & Interior Design",
        "Camera Installation",
        "Car Rental",
        "Car Services",
        "Catering & Restaurant",
        "Construction Services",
        "Consultancy Services",
        "Domestic Help",
        "Drivers & Taxi",
        "Tuitions & Academies",
        "Electronics & Computer Repair",
        "Event Services",
        "Farm & Fresh Food",
        "Health & Beauty",
        "Home & Office Repair",
        "Insurance Services",
        "Movers & Packers",
        "Renting Services",
        "Tailor Services",
        "Travel & Visa",
        "Video & Photography",
        "Web Development",
        "Other Services",
      ],
      options: {
        "Domestic Help": [
          "Maids",
          "Babysitters",
          "Cooks",
          "Nursing Staff",
          "Other Domestic Help",
        ],
        "Drivers & Taxi": ["Drivers", "Pick & Drop", "Carpool"],
        "Health & Beauty": [
          "Beauty & Spa",
          "Fitness Trainers",
          "Health Services",
        ],
        "Home & Office Repair": [
          "Painters",
          "Electricians",
          "Plumbers",
          "Carpenters",
          "Pest Control",
          "Water Tank Cleaning",
          "Deep Cleaning",
          "Geyser Services",
          "AC Services",
          "Other Repair Services",
        ],
      },
    },
    Jobs: {
      title: [
        "Accounting & Finance",
        "Advertising & PR",
        "Architecture & Interior Design",
        "Clerical & Administration",
        "Content Writing",
        "Customer Service",
        "Delivery Riders",
        "Domestic Staff",
        "Education",
        "Engineering",
        "Graphic Design",
        "Hotels & Tourism",
        "Human Resources",
        "Internships",
        "IT & Networking",
        "Manufacturing",
        "Marketing",
        "Medical",
        "Online",
        "Other Jobs",
        "Part Time",
        "Real Estate",
        "Restaurants & Hospitality",
        "Sales",
        "Security",
      ],
    },
    Animals: {
      title: [
        "Cats",
        "Dogs",
        "Horses",
        "Rabbits",
        "Other Animals",
        "Hens",
        "Parrots",
        "Pigeons",
        "Finches",
        "Doves",
        "Peacocks",
        "Ducks",
        "Other Birds",
        "Fertile Eggs",
        "Fish",
        "Livestock",
        "Pet Food & Accessories",
      ],
      options: {
        Livestock: [
          "Buffalos",
          "Bulls",
          "Camels",
          "Cows",
          "Goats",
          "Sheep",
          "Others",
        ],
        "Pet Food & Accessories": [
          "Cat Food",
          "Cat Accessories",
          "Dog Food",
          "Dog Accessories",
          "Fish Food",
          "Aquariums",
          "Incubators",
          "Brooders",
          "Hen Cages",
          "Birds Food",
          "Birds Accessories",
          "Other Animal Food & Accessories",
          "Medicines",
        ],
      },
    },
    "Furniture & Home Decor": {
      title: [
        "Sofa & Chairs",
        "Beds & Wardrobes",
        "Tables & Dining",
        "Bathroom Accessories",
        "Garden & Outdoor",
        "Painting & Mirrors",
        "Rugs & Carpets",
        "Curtains & Blinds",
        "Office Furniture",
        "Home Decoration",
        "Other Household Items",
      ],
      options: {
        "Sofa & Chairs": [
          "Sofas",
          "Sofa Beds",
          "Sofa Covers",
          "Cushions",
          "Chairs",
          "Recliners",
          "Bean Bags",
        ],
        "Beds & Wardrobes": [
          "Beds",
          "Mattresses",
          "Mattress Covers",
          "Pillows & Cases",
          "Bed Sheets",
          "Blankets & Comforters",
          "Other Bedding Accessories",
          "Wardrobes",
        ],
        "Bathroom Accessories": [
          "Basins",
          "Bath Cabinets",
          "Bath Towels",
          "Bath Tubs",
          "Shower Cabins",
          "Soap Dispensers",
          "Taps",
          "Toilets",
          "Vanity Units",
          "Other Bathroom Accessories",
        ],
        "Garden & Outdoor": [
          "Artificial Grass",
          "Benches",
          "Outdoor Chairs",
          "Outdoor Tables",
          "Outdoor Fountains",
          "Outdoor Lights",
          "Outdoor Umbrellas",
          "Outdoor Swings",
          "Plants & Pots",
          "Tents & Shades",
          "Other Outdoor Items",
        ],
        "Painting & Mirrors": [
          "Paintings",
          "Painting Accessories",
          "Frames",
          "Mirror Lights",
          "Mirrors",
        ],
        "Rugs & Carpets": ["Rugs", "Carpets", "Mats", "Prayer Mats"],
        "Curtains & Blinds": ["Curtains", "Blinds", "Curtain Accessories"],
        "Office Furniture": [
          "Office Chairs",
          "Office Sofas",
          "Office Tables",
          "Shelves & Racks",
          "Office Cabinets",
          "Other Office Furniture",
        ],
        "Home Decoration": [
          "Artificial Flowers & Plants",
          "Candles",
          "Chandeliers",
          "Decorative Trays",
          "Handicrafts",
          "Indoor Fountains",
          "Lamps",
          "Tissue Boxes",
          "Sculptures",
          "Showpieces",
          "Vases",
          "Flooring",
          "Wall Clocks",
          "Wall Hangings",
          "Wall Lights",
          "Other Decor Items",
        ],
      },
    },
    "Fashion & Beauty": {
      title: [
        "Fashion Accessories",
        "Clothes",
        "Footwear",
        "Bags",
        "Jewellery",
        "Makeup",
        "Skin & Hair",
        "Watches",
        "Fragrance",
        "Wedding",
        "Other Fashion",
      ],
      options: {
        "Fashion Accessories": [
          "Caps",
          "Scarves",
          "Ties",
          "Belts",
          "Socks",
          "Gloves",
          "Cufflinks",
          "Sunglasses",
        ],
        Clothes: [
          "Eastern",
          "Western",
          "Hijabs & Abayas",
          "Sports Clothes",
          "Kids Clothes",
        ],
        Makeup: [
          "Brushes",
          "Eyes",
          "Face",
          "Lips",
          "Nails",
          "Other Makeup Accessories",
        ],
        "Skin & Hair": ["Hair Care", "Skin Care"],
        Wedding: ["Bridals", "Grooms", "Formals"],
      },
    },
    "Books, Sports & Hobbies": {
      title: [
        "Books & Magazines",
        "Musical Instruments",
        "Sports Equipment",
        "Gym & Fitness",
        "Other Hobbies",
      ],
      options: {
        "Books & Magazines": [
          "Books",
          "Magazines",
          "Dictionaries",
          "Stationery Items",
          "Calculators",
        ],
      },
    },
    Kids: {
      title: [
        "Kids Furniture",
        "Kids Vehicles",
        "Toys",
        "Baby Gear",
        "Bath & Diapers",
        "Swings & Slides",
        "Kids Clothing",
        "Kids Accessories",
      ],
      options: {
        "Kids Vehicles": [
          "Kids Bikes",
          "Kids Cars",
          "Kids Cycles",
          "Kids Scooties",
        ],
        "Baby Gear": [
          "Baby Bouncers",
          "Prams & Walkers",
          "Baby Carriers",
          "Baby Cots",
          "Baby Swings",
          "Car Seats",
          "High Chairs",
          "Other Baby Gear",
        ],
        "Kids Clothing": [
          "Kids Costumes",
          "Kids Clothes",
          "Kids Shoes",
          "Kids Uniforms",
          "Others",
        ],
      },
    },
  },
];
